// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import EditHomepageController from "./edit_homepage_controller"
application.register("edit-homepage", EditHomepageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MediaController from "./media_controller"
application.register("media", MediaController)
